SELECT [Id]
      ,[Name]
      ,[RevevantNames]
      ,[Code]
      ,[CreatedBy]
      ,[CreatedAt]
      ,[UpdatedBy]
      ,[UpdatedAt]
      ,[CountryId]
      ,[CurrencyId]
      ,[CurrencyCode]
      ,[CultureFormat]
  FROM [dbo].[Country]