WITH tmp AS (
	SELECT [Id]
		  , [Name]
		  , [RevevantNames]
		  , [Code]
		  , [CreatedBy]
		  , CONVERT(DATETIME, [CreatedAt]) AS [CreatedAt]
		  , [UpdatedBy]
		  , CONVERT(DATETIME, [UpdatedAt]) AS [UpdatedAt]
		  , [CountryId]
		  , COALESCE([CurrencyId], -100) AS [CurrencyId]
		  , [CurrencyCode]
		  , [CultureFormat]
		  , CONVERT(DATETIME, COALESCE([UpdatedAt], [CreatedAt])) AS [Trigger_UpdatedAt]
	FROM [dbo].[Country]
)
SELECT [Id]
      , [Name]
      , [RevevantNames]
      , [Code]
      , [CreatedBy]
      , [CreatedAt]
      , [UpdatedBy]
      , [UpdatedAt]
      , [CountryId]
      , [CurrencyId]
      , [CurrencyCode]
      , [CultureFormat]
	  , [Trigger_UpdatedAt]
FROM tmp