WITH tmp AS (
	SELECT [Id]
		, [Name]
		, [RelevantNames]
		, [CountryId]
		, COALESCE([StateId], -100) AS [StateId]
		, COALESCE([RegionId], -100) AS [RegionId]
		, COALESCE([CreatedBy], -100) AS [CreatedBy]
		, CONVERT(DATETIME, [CreatedAt]) AS [CreatedAt]
		, COALESCE([UpdatedBy], -100) AS [UpdatedBy]
		, CONVERT(DATETIME, [UpdatedAt]) AS [UpdatedAt]
		, CONVERT(DATETIME, COALESCE([UpdatedAt], [CreatedAt])) AS [Trigger_UpdatedAt]
	FROM [dbo].[City]
)
SELECT [Id]
	, [Name]
	, [RelevantNames]
	, [CountryId]
	, [StateId]
	, [RegionId]
	, [CreatedBy]
	, [CreatedAt]
	, [UpdatedBy]
	, [UpdatedAt]
	, [Trigger_UpdatedAt]
FROM tmp