SELECT [Id]
      , [Name]
      , [RelevantNames]
      , [CountryId]
      , [StateId]
      , [RegionId]
      , [CreatedBy]
      , [CreatedAt]
      , [UpdatedBy]
      , [UpdatedAt]
	  , COALESCE([UpdatedAt], [CreatedAt]) AS Trigger_UpdatedAt
  FROM [dbo].[City]