WITH tmp AS (
	SELECT [Id]
	  , [PharmacyId]
	  , CAST([IsMain] AS INT) AS [IsMain]
	  , COALESCE([StateId], -100) AS [StateId]
	  , COALESCE([CountryId], -100) AS [CountryId]
	  , COALESCE([RegionId], -100) AS [RegionId]
	  , COALESCE([CityId], -100) AS [CityId]
	  , COALESCE([DistrictId], -100) AS [DistrictId]
	  , CAST([Active] AS INT) AS [Active]
	  , [Detail]
	  , [FullAddress]
	  , COALESCE([CreatedBy], -100) AS [CreatedBy]
	  , CONVERT(DATETIME, [CreatedAt]) AS [CreatedAt]
	  , COALESCE([UpdatedBy], -100) AS [UpdatedBy]
	  , CONVERT(DATETIME, [UpdatedAt]) AS [UpdatedAt]
	  , COALESCE([WardId], -100) AS [WardId]
	  , [Detail1]
	  , [Detail2]
	  , [Detail3]
	  , [Detail4]
	  , [DetailNoted]
	  , CONVERT(DATETIME, COALESCE([UpdatedAt], [CreatedAt])) AS [Trigger_UpdatedAt]
	FROM [dbo].[PharmacyAddress]
)
SELECT [Id]
    , [PharmacyId]
    , [IsMain]
    , [StateId]
    , [CountryId]
    , [RegionId]
    , [CityId]
    , [DistrictId]
    , [Active]
    , [Detail]
    , [FullAddress]
    , [CreatedBy]
    , [CreatedAt]
    , [UpdatedBy]
    , [UpdatedAt]
    , [WardId]
    , [Detail1]
    , [Detail2]
    , [Detail3]
    , [Detail4]
    , [DetailNoted]
	, [Trigger_UpdatedAt]
FROM tmp