SELECT [Id]
      ,[FirstName]
      ,[LastName]
      ,[UserId]
      ,[HasRegisterCode]
      ,[PharmacyId]
      ,[Active]
      ,[PositionId]
      ,[CreatedBy]
      ,[CreatedAt]
      ,[UpdatedBy]
      ,[UpdatedAt]
      ,[RegisteredBy]
      ,[RegisteredDate]
      ,[CountryId]
      ,[UseTempPassword]
      ,[IsGeneric]
      ,[AlreadyLoggedIn]
  FROM [dbo].[PharmacyEmployee]