WITH tmp AS (
	SELECT [Id]
		, [FirstName]
		, [LastName]
		, COALESCE([UserId], -100) AS [UserId]
		, CAST([HasRegisterCode] AS INT) AS [HasRegisterCode]
		, [PharmacyId]
		, CAST([Active] AS INT) AS [Active]
		, [PositionId]
		, COALESCE([CreatedBy], -100) AS [CreatedBy]
		, CONVERT(DATETIME, [CreatedAt]) AS [CreatedAt]
		, COALESCE([UpdatedBy], -100) AS [UpdatedBy]
		, CONVERT(DATETIME, [UpdatedAt]) AS [UpdatedAt]
		, COALESCE([RegisteredBy], -100) AS [RegisteredBy]
		, CONVERT(DATETIME, [RegisteredDate]) AS [RegisteredDate]
		, [CountryId]
		, CAST([UseTempPassword] AS INT) AS [UseTempPassword]
		, CAST([IsGeneric] AS INT) AS [IsGeneric]
		, CAST([AlreadyLoggedIn] AS INT) AS [AlreadyLoggedIn]
		, CONVERT(DATETIME, COALESCE([UpdatedAt], [CreatedAt])) AS [Trigger_UpdatedAt]
	FROM [dbo].[PharmacyEmployee]
)
SELECT [Id]
    , [FirstName]
    , [LastName]
    , [UserId]
    , [HasRegisterCode]
    , [PharmacyId]
    , [Active]
    , [PositionId]
    , [CreatedBy]
    , [CreatedAt]
    , [UpdatedBy]
    , [UpdatedAt]
    , [RegisteredBy]
    , [RegisteredDate]
    , [CountryId]
    , [UseTempPassword]
    , [IsGeneric]
    , [AlreadyLoggedIn]
    , [Trigger_UpdatedAt]
FROM tmp